export const Events = {
  REQUEST_SUBMITTED: 'REQUEST_SUBMITTED',
  REQUEST_ACCEPTED: 'REQUEST_ACCEPTED',
  QUOTE_SENT: 'QUOTE_SENT',
  QUOTE_ACCEPTED: 'QUOTE_ACCEPTED',
  MESSAGE_NEW: 'MESSAGE_NEW',
  INVOICE_ISSUED: 'INVOICE_ISSUED',
  PAYMENT_SUCCEEDED: 'PAYMENT_SUCCEEDED',
  ASSET_PREVIEW_READY: 'ASSET_PREVIEW_READY'
} as const
